### ISSUE TITLE
I can't still get it working with the new update

### ISSUE THREAD

**Issue by Shnxxx** [OtaK/timertool-rs#3]
I tried running different flags through an elevated CMD but it doesn't print anything.

### Steps to Reproduce:

1. I renamed `timerset_windows_v0.3.0.exe` to `timerset.exe`
2. run CMD as administrator
3. Then go to the directory where the `timerset.exe` is. `cd "C:\Users\BLANK\Downloads\Programs"
4. Then type, `timerset.exe --install --islc`
5. Try different flags, `timerset.exe --help`, `timerset.exe -h`, `timerset.exe --values`, `timerset.exe -v`, etc...

### Expected behaviour:

Should display/prints values and other information. Also, `timerset.exe` should be seen in the Task Manger under `details`.

### Actual behavior:

Doesn't do anything. It doesn't print any information. If you tried `timerset.exe --install`, it doesn't run or being registered in Task Manager processes under `details` tab.

### Environment

* timertool-rs version: timerset_windows_v0.3.0.exe
* Operating System and version: Windows 10 2004 (OS Build 19041.685)

![image](https://user-images.githubusercontent.com/48496678/107100321-fa3d6f00-684e-11eb-9660-2c36f6c882c4.png)

Am I missing something? Thank you again!

**Comment by OtaK** [comment]
Is the `Start TimerSet` task present in the Task Scheduler?

The fact that the program doesn't print anything is "normal"; That's actually a Windows issue rather than a program issue. See: https://github.com/rust-lang/rfcs/blob/master/text/1665-windows-subsystem.md

Otherwise the console would pop-up constantly when using such a program, but the bad part is that it prevents the program from outputting anything when used from the command line.

**Comment by OtaK** [comment]
For the record: I just released version 0.4.0 that contains a dual logger; Log output on release versions would be done in a .log file next to the executable.
I also added a --pretend flag to help in knowing what the program does without modifying your system.

**Comment by Shnxxx** [comment]
So I tested the latest release. Installed it through cmd: `timerset_windows_v0.4.0.exe --install --islc` and produced a `.log` as you said. Based on the `.log` file, it seems it installed successfully since `C:\Program Files\TimerSet\TimerSet.exe` exists. But I am still not sure since it doesn't appear on the Task Manager under `Details`. It only appeared after running it (double-clicking the `.exe`).
Do I need to run it every time Windows starts up?

> Is the `Start TimerSet` task present in the Task Scheduler?
About this, I couldn't find any scheduled task about `TimerSet`. I tried looking it up under `Task Scheduler (Local)` and also under `Task Scheduler Library`.
Here are the scheduled task under `Task Scheduler Library`.
![image](https://user-images.githubusercontent.com/48496678/112511409-59d6e600-8dcd-11eb-9fe0-7cae0a583c2a.png)

**Comment by garoto** [comment]
Piping the program output to a pager-like program will render to the console/terminal. The Windows built-in `more.com` is the best candidate:

```powershell
> F:\Downloads\timerset_windows_v0.4.0.exe --pretend | more
[timerset] INFO > --pretend enabled, no action will be taken on the system
[timerset] INFO > System Timer Values: min [156250μs] / max [5000μs] / cur [5000μs]
[timerset] INFO > Chosen timer value: 5000μs
[timerset] INFO > New timer value set: 5000μs
```
